// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzyuhvxupgqbrurfrijk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16eXVodnh1cGdxYnJ1cmZyaWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjc4NzgsImV4cCI6MjA3MTg0Mzg3OH0.pHFr9FCuVK-t4UOyHedQiHHLPd1-3BAmkLd2L5qIyfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});